### PR TITLE
metal pixelFormat must be BGRA on macOS 12

### PR DESCRIPTION
**Pull request by crowell**
i believe this shouldn't break anything on macOS 13, but please let me
know!

### CODE REVIEW

**Comment by crowell** [comment]
if i just set the pixelformat to BGRA, then colors are inverted, this changes the pixel format, and also swaps the float4 in the fragment shader.

was getting this error before

```
[2022-07-24 23:46:43.435] [/Users/jeff/dev/oot/XCShipwright/libultraship/libultraship/ResourceMgr.cpp:107] [info] Resource Manager LoadResourceThread started
2022-07-24 23:46:43.563182-0400 soh[11482:82945] Metal GPU Frame Capture Enabled
2022-07-24 23:46:43.604313-0400 soh[11482:82945] [General] An uncaught exception was raised
2022-07-24 23:46:43.604454-0400 soh[11482:82945] [General] invalid pixel format 70
2022-07-24 23:46:43.604559-0400 soh[11482:82945] [General] (
	0   CoreFoundation                      0x00000001c44b9198 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x00000001c4203e04 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001c44b8fe4 +[NSException exceptionWithName:reason:userInfo:] + 0
	3   QuartzCore                          0x00000001cb2bce8c -[CAMetalLayer setPixelFormat:] + 292
	4   soh                                 0x00000001013928c0 _Z10Metal_Initv + 64
	5   soh                                 0x000000010125107c _ZN8SohImGui16ImGuiBackendInitEv + 84
	6   soh                                 0x00000001012525a0 _ZN8SohImGui4InitENS_10WindowImplE + 496
	7   soh                                 0x00000001012c6404 _ZL12gfx_sdl_initPKcS0_bjj + 828
	8   soh                                 0x00000001012ac448 _Z8gfx_initP19GfxWindowManagerAPIP15GfxRenderingAPIPKcbjj + 160
	9   soh                                 0x0000000101502838 _ZN4Ship6Window4InitEv + 808
	10  soh                                 0x000000010053e484 _ZN10OTRGlobalsC2Ev + 240
	11  soh                                 0x000000010053e814 _ZN10OTRGlobalsC1Ev + 28
	12  soh                                 0x000000010053f274 InitOTR + 40
	13  soh                                 0x000000010070a100 main + 28
	14  dyld                                0x000000010428508c start + 520
)
2022-07-24 23:46:43.604857-0400 soh[11482:82945] *** Terminating app due to uncaught exception 'CAMetalLayerInvalid', reason: 'invalid pixel format 70'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001c44b9198 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x00000001c4203e04 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001c44b8fe4 +[NSException exceptionWithName:reason:userInfo:] + 0
	3   QuartzCore                          0x00000001cb2bce8c -[CAMetalLayer setPixelFormat:] + 292
	4   soh                                 0x00000001013928c0 _Z10Metal_Initv + 64
	5   soh                                 0x000000010125107c _ZN8SohImGui16ImGuiBackendInitEv + 84
	6   soh                                 0x00000001012525a0 _ZN8SohImGui4InitENS_10WindowImplE + 496
	7   soh                                 0x00000001012c6404 _ZL12gfx_sdl_initPKcS0_bjj + 828
	8   soh                                 0x00000001012ac448 _Z8gfx_initP19GfxWindowManagerAPIP15GfxRenderingAPIPKcbjj + 160
	9   soh                                 0x0000000101502838 _ZN4Ship6Window4InitEv + 808
	10  soh                                 0x000000010053e484 _ZN10OTRGlobalsC2Ev + 240
	11  soh                                 0x000000010053e814 _ZN10OTRGlobalsC1Ev + 28
	12  soh                                 0x000000010053f274 InitOTR + 40
	13  soh                                 0x000000010070a100 main + 28
	14  dyld                                0x000000010428508c start + 520
)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'CAMetalLayerInvalid', reason: 'invalid pixel format 70'
terminating with uncaught exception of type NSException
```

**Comment by crowell** [comment]
image
with this change, some things that are rendered by ImGui are still off. unsure why still though.

**Comment by dcvz** [comment]
> image with this change, some things that are rendered by ImGui are still off. unsure why still though.

You want to make the same change in `imgui_impl_metal.mm` that's where they also set their shader code.

**Comment by dcvz** [comment]
@crowell the interesting this is that if you look at their example `ImGui/examples/example_sdl_metal/main.mm` they also use `MTLPixelFormatBGRA8Unorm` without having to modify their shader code.. maybe there's something simpler.

Either way what you have here works too

**Comment by dcvz** [comment]
Fixes #16

**Comment by crowell** [comment]
this is ready to go!

**Pull request merged**
